#!/usr/bin/env python

import json
import locale
import sys
import reports
import os
import emails

def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    new_data = json.load(json_file)
    data = sorted(new_data, key=lambda x: x["total_sales"])
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(
      car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}
  max_sales = {"total_sales" : 0}
  max_popular = {}
  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_sales = item["total_sales"]
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item
    # TODO: also handle max sales
    if item_sales > max_sales["total_sales"]:
        max_sales = item
    # TODO: also handle most popular car_year
    if not item["car"]["car_year"] in max_popular.keys():
        max_popular[item["car"]["car_year"]] = item["total_sales"]
    else:
        max_popular[item["car"]["car_year"]] += item["total_sales"]
    
    #get most popular
    all_values = max_popular.values()
    max_value = max(all_values)
    max_key = max(max_popular, key=max_popular.get)

  summary = [
    "The {} generated the most revenue: ${}".format(
      format_car(max_revenue["car"]), max_revenue["revenue"]),
    "The{} had the most sales: {}".format(format_car(max_sales["car"]), max_sales["total_sales"]),
    "The most popular year was {} with {} sales.".format(max_key, max_value),
  ]

  return summary
    # return max_revenue["revenue"]


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data


def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("car_sales.json")
  summary = process_data(data)
  print(summary)
  new_summary = "<br/>".join(summary) + "<br/>"
  # TODO: turn this into a PDF report
  reports.generate("C:/Users/ASUS/coursera/auto/week3/actual/scripts/cars3.pdf","Cars Report", new_summary,cars_dict_to_table(data) )
  
  


  # reports.generate("/tmp/cars.pdf","Cars Report", new_summary,cars_dict_to_table(data) )
  # # TODO: send the PDF report as an email attachment
  sender = "automation@example.com"
  receiver = "{}@example.com".format("student-02-37474229022a")
  subject = "Sales summary for last month"
  body = "\n".join(summary)

  message = emails.generate(sender, receiver, subject, body, "/tmp/cars.pdf")
  emails.send(message)

if __name__ == "__main__":
  main(sys.argv)